#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

./gradlew assembleRelease

rm -rf build
mkdir build

cp keeva/build/outputs/aar/keeva-release.aar build/

cd - > /dev/null
