#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

# filename="SoomlaAndroidCore"
# rm -rf build/
# mkdir build
# ant -buildfile soomla-android-core.xml -Dsoomla.filename="$filename" all
./gradlew assembleRelease

cd - > /dev/null
